### ISSUE TITLE
Code to reformat table generates unwanted characters

### ISSUE THREAD

**Issue by lextm** [TatsuyaNakamori/vscode-reStructuredText#1]
While investigating [an issue](https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/329) of Table Editor, I noticed that several lines around [this](https://github.com/TatsuyaNakamori/vscode-reStructuredText/blob/1b72827cb18ae075e94dfdf82101e6fe3b299a4b/src/tableEditor.ts#L264) tries to insert `|` while the purpose is unclear.

I made some changes in [this commit](https://github.com/vscode-restructuredtext/vscode-restructuredtext/commit/725c74420b6d616491c6ee69e62891236a1251fa) and hope it is the right way to resolve the issue.

**Comment by TatsuyaNakamori** [comment]
Thanks for the bug report.
I will check it out.

**Comment by TatsuyaNakamori** [comment]
Does the "list" described in [this bug report](https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/329)  refer to the "Cell" in the table? 
(The term "list" gets mixed up with the way it's displayed [here](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#lists-and-quote-like-blocks) , so I'll just call it "Cell" as in Excel.)

The double "|" is not a bug, it is intentional to create a line break when rendered.

If there is a single "|", the text will be displayed as two lines in reStructuredText, but when it is converted to HTML, it will be concatenated into one line.
This causes the problem of different display.

I believe that the display of reStructuredText and the display when converted to HTML, etc. should match as much as possible.
(I understand that you may want to write on a new line to make it easier to understand...)

So, unfortunately, I cannot agree with this change.

If there is a way to make both single and double |, I may develop a new one.
Do you have any good ideas?
(Do you want to allow users to choose between single and double in the user definition?)

![pic_266](https://user-images.githubusercontent.com/48149444/140677168-9b34b2c2-ec77-4631-aa84-35ca19236f4a.png)
![pic_267](https://user-images.githubusercontent.com/48149444/140677172-5169bf6a-c440-42ba-993c-9e3c3a30bcc9.png)

**Comment by TatsuyaNakamori** [comment]
Close for lack of progress.

**Comment by lextm** [comment]
Thanks for explaining the original design. I can now see why `||` is important in formatting, so I will revert the changes (which now turns out to be on the wrong direction).
